Project initialization
vketrys/nodejs-app pull request #1
Opened 2022-12-10 13:04 UTC by vketrys

- [ ] Create node.js TypeScript app
- [ ] Configuration
- [ ] Adding linters

2022-12-12 16:27 UTC, esinitsa requested changes

2022-12-12 16:27 UTC, esinitsa commented on package.json
> +    "dev": "nodemon ./dist/index.js",
why we are using index.js instead of .ts file?

2022-12-12 16:27 UTC, esnts commented on package.json
> +    "@types/express": "^4.17.14",
remove version autoincrementation

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +  signInWithEmailAndPassword
LINT?

2022-12-12 16:27 UTC, esnts commented on src/auth.ts
> +export const signup = (req, res) => {
signup type? 
req type? 
res type?

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +export const signup = (req, res) => {
export const signup = ({body : {.....}}, res) => {

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +    return res.status(422).json({
422 -> constants

2022-12-12 16:27 UTC, esnts commented on src/auth.ts
> +      email: 'email is required',
`email is required` to C
...

2022-12-12 16:27 UTC, esnts commented on src/auth.ts
> +export const signup = (req, res) => {
try catch finally(optional)

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +import app from './config/firebase.js';
WHY JS? WTFFFFF???

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +      return res.status(201).json(data);
201 - C

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +      if (error.code == 'auth/weak-password') {
Can you get this S from node_module ? 'auth/weak-password'

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +      if (error.code == 'auth/weak-password') {
or -> C

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +      if (error.code == 'auth/weak-password') {
===

2022-12-12 16:27 UTC, esinitsa commented on src/auth.ts
> +      if (error.code == 'auth/weak-password') {
return res.status(500).json({ error: error.message });

2022-12-12 16:27 UTC, esinitsa commented on src/index.ts
> +  console.log(`app listening on port ${port}`);
NO LOGS

2022-12-12 16:27 UTC, esinitsa commented on src/index.ts
> +  console.log(`app listening on port ${port}`);
+ log to output file

2022-12-12 16:27 UTC, esinitsa commented on src/index.ts
> +app.use("/api", authRoutes);
-> C

2022-12-12 16:27 UTC, esinitsa commented on src/routes/routes.ts
> +router.post("/signup", signup);
/signup -> C 

const URL = {
ROOT : "/api",
AUT: {
SIGNIN: '/signin'
} 
}

2022-12-15 18:19 UTC, esnts approved these changes
LGTM

2022-12-15 18:19 UTC, esinitsa commented on src/auth.ts
> +		const { email, password } = req.body;
tab 8 symbols? super strange

2022-12-15 18:19 UTC, esnts commented on src/auth.ts
> +			return res.status(statusCodes.unprocessableEntity).json({
never send passwords

2022-12-15 18:19 UTC, esnts commented on src/auth.ts
> +			.then((user) => {
попробуй найти правило для линта. не оборачивать функцию в скобки если там только ретурн

2022-12-15 18:19 UTC, esinitsa commented on src/auth.ts
> +		if (error.code === errorCodes.weakPassword) {
res.status(error.code === errorCodes.weakPassword ? statusCodes.badRequest : .... )
   .json({ error: error.message });
   
or

create const for error.code === errorCodes.weakPassword ? statusCodes.badRequest :

2022-12-15 18:19 UTC, esinitsa commented on src/auth.ts
> +			.then((user) => {
Какой тип юзера, мы точно не отправляем лишней информации?

2022-12-15 18:19 UTC, esinitsa commented on src/config/firebase.ts
> +	apiKey: process.env.API_KEY,
NICE

2022-12-15 18:19 UTC, esinitsa commented on src/constants/URL.ts
> +		SIGNIN: '/signin',
nice

2022-12-15 18:19 UTC, esinitsa commented on src/index.ts
> +const port = process.env.PORT || 3000;
nice

2022-12-16 13:21 UTC, slamser56 approved these changes

2022-12-21 16:45 UTC, merged